### ISSUE TITLE
Not able to run 

### ISSUE THREAD

**Issue by prabhatjon** [njmarko/googolplex-pdf-search#1]
while running code getting thsi error 
c:\myenv\googolplex-pdf-search-master\main.py:38: SyntaxWarning: invalid escape sequence '\_'
  print("""  /$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$  /$$       /$$$$$$$  /$$       /$$$$$$$$ /$$   /$$
Traceback (most recent call last):
  File "c:\myenv\googolplex-pdf-search-master\main.py", line 15, in <module>
    from fitz import fitz, PDF_ENCRYPT_KEEP  # pip install PyMuPDF
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'fitz' from 'fitz' (C:\myenv\Lib\site-packages\fitz\__init__.py)

**Comment by njmarko** [comment]
For that print, you can try putting r in front of the string.

`print(r""" /$$$$$$  /$$$$$$  /$$$$$$  /$$$$$$  /$$$$$$  /$$ /$$$$$$$  /$$ /$$$$$$$$ /$$ /$$""")`

As for the import, try installing PyMuPDF. I ran that code a long time ago, but I left a comment about what library to install there.

`pip install PyMuPDF`

**Comment by prabhatjon** [comment]
thanks for the quick response, yes that helps but the new error like 
Traceback (most recent call last):
  File "c:\myenv\googolplex-pdf-search-master\main.py", line 14, in <module>
    from fitz import fitz, PDF_ENCRYPT_KEEP  # pip install PyMuPDF
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'fitz' from 'fitz' (C:\myenv\Lib\site-packages\fitz\__init__.py)

**Comment by njmarko** [comment]
Did you install fitz?

I think maybe you can uninstall it, and install PyMuPDF again.

**Comment by prabhatjon** [comment]
Yes I did, I have tried after uninstalling and re installing it but the error still remains

**Comment by njmarko** [comment]
I added instructions to the readme file.

I also added requirements.txt, and I fixed some imports. It works for me now on my machine.

Try it out now by following the instructions in the readme.
